[HPRO-300] Switch to git-secrets for private key detection
This switches us to use the more standardized `git-secrets` binary for
scanning repositories for accidentally committed keys. The patterns are
borrowed from the Workbench team.

Note that the Homebrew installed version has a bug in it that requires
you to build directly from master. Per this
[workaround](https://github.com/awslabs/git-secrets/issues/65#issuecomment-446519551),
you can install a working version via:

```bash
brew install git-secrets --HEAD
```

[[HPRO-300](https://precisionmedicineinitiative.atlassian.net/browse/HPRO-300)]

diff --git a/bin/installHooks b/bin/installHooks
--- a/bin/installHooks
+++ b/bin/installHooks
@@ -1,13 +1,17 @@
-#!/bin/bash
+#!/usr/bin/env bash
+set -euo pipefail
+IFS=$'\n\t'
 
-APP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
+{ which git-secrets; } || {
+  echo 'git-secrets required and not found. See README for installation instructions.'
+  echo
+  exit 1
+}
 
-echo "installHooks: adding git hooks for development ..."
-if [ -f "${APP_DIR}/.git/hooks/pre-commit" ]
-then
-  echo "installHooks: pre-commit script already installed."
-else
-  cp ${APP_DIR}/bin/git-hooks/pre-commit ${APP_DIR}/.git/hooks/pre-commit
-  chmod +x ${APP_DIR}/.git/hooks/pre-commit
-  echo "installHooks: done!"
-fi
+{
+  git config --remove-section secrets 2>/dev/null
+} || {
+  :
+}
+git secrets --add '"private_key":'
+git secrets --add --allowed 'git secrets --add *'
